# Site configuration
title: Laboratorio de Autoacceso
email: autoacceso@cs.buap.mx
description: Laboratorio, Autoacceso, proyectos
baseurl:
url: "/"

sass:
    style: compressed

exclude: [Dockerfile, README.md]
