# Site configuration
title: Laboratorio de Autoacceso
email: autoacceso@cs.buap.mx
description: laboratorio, autoacceso, proyectos # TODO: Change
baseurl:
url: "/"

sass:
  style: compressed

exclude:
  - Dockerfile
  - README.md
