# Site configuration
title: Laboratorio de Autoacceso
email: autoacceso@cs.buap.mx
description: >
  Laboratorio enfocado en la investigación y desarrollo de proyectos
  de la Benemerita Universidad Autonoma de Puebla.
baseurl: ""
url: "/"

sass:
  style: compressed

exclude:
  - Dockerfile
  - README.md
